### ISSUE TITLE
Config not saving. 

### ISSUE THREAD

**Issue by Stevofpv** [flyandi/SquidRID#4]
I’m running an esp32c3.   I’m able to configure it using web but after disconnecting from pc the config is lost.   When running drone scanner on android it only shows 4 drones of which two of them are unknown when not connected to the pc.   When it is connected to the pc it works good and runs how the config is setup.  The latest esp32 is uploaded.   Any ideas?

**Comment by flyandi** [comment]
What are your Arduino settings for the board? 

When you configure via the web - the chip actually does what you suppose to do? 

Make sure u have these settings when uploading it:

![image](https://github.com/flyandi/SquidRID/assets/329973/e6d3eaa3-b4c6-421e-b5c2-a14755490e75)

**Comment by flyandi** [comment]
U have to have SPIFFS enabled!

**Comment by Stevofpv** [comment]
I will take a look when I get home tonight.   The overall code/configurator is very impressive.  Thanks.

**Comment by Stevofpv** [comment]
yeah my the spiffs are enables as you have listed.  I'd using the hardware version and not the web version if that makes a difference?  Did you have to add a plug in for the spiffs

**Comment by rrittenhouse** [comment]
I have ESP32-C3's that I've tried it on and I am having issues where I just get unknown locations for "unknown drones" even though I specify it in the web UI. I haven't actually been able to get it to "work" correctly yet.

**Comment by Stevofpv** [comment]
> I have ESP32-C3's that I've tried it on and I am having issues where I just get unknown locations for "unknown drones" even though I specify it in the web UI. I haven't actually been able to get it to "work" correctly yet.

Yeah.   It works for me as long as I don’t unplug it from the configurator.  When it’s plugged into the config via web it functions as designed with generated drone ids.   If I leave it plugged in but exit the configurator it generates unknown remote ids.   If I unplug it from the usb and then plug it back in it shows 4 unknown remote ids but stays resorts back to squid mode from pest mode.  Seems to reset the number of drones at 100 and starts from zero regardless.

**Comment by rrittenhouse** [comment]
@Stevofpv I can't get the apps to recognize the LAT/LON that I'm entering unless there's a different format than XX.XXXXXX and -XX.XXXXXX for the operator OR the drone. Different issue all together then. I hope you get yours figured out. I'll work on this a little bit later again to see what I may have done wrong for my case.

**Comment by Stevofpv** [comment]
> @Stevofpv I can't get the apps to recognize the LAT/LON that I'm entering unless there's a different format than XX.XXXXXX and -XX.XXXXXX for the operator OR the drone. Different issue all together then. I hope you get yours figured out. I'll work on this a little bit later again to see what I may have done wrong for my

**Comment by Stevofpv** [comment]
It seems to me the configurator isnt communicating with the  spiff

**Comment by truglodite** [comment]
I just observed what I think is related behavior on my local configurator instance. I did a fresh reflash, erasing the chip first. After connecting and configuring my external gps and hitting apply, the configurator started not making sense... I also saw coords in Africa. Upon powering off the device, refreshing the page, plugging back in, reconnecting... at first my gps and rest of the profile appeared blank. So I clicked cancel, waited like 10 sec, opened the profile again and now the gps config, operator coords, etc were populated. So not 100% sure, but it could be that you are trying to access the profile before necessary comms are finished when connecting to the configurator.

**Comment by rrittenhouse** [comment]
@truglodite This is what I am having issues with. It seems like the device doesn't do anything in conjunction with the configurator. It feels like nothing is working and the configurator has the locations in africa here as well almost like it's not saving the coords or saving them at all?

**Comment by Stevofpv** [comment]
Seems to be a hardware/firmware vs sketch issue.  I just uploaded the sketch onto a hiletgo 32esp wroom-32u dev board and it’s working flawless.  It’s populating uids for every drone and is respecting config settings after power cycle.  For anyone looking for one this specific board offers a way to attach an external antenna 👍🏻

**Comment by rrittenhouse** [comment]
> 

Nice. I'll have to send these back (which I ordered for this purpose) and try to grab those instead. I like the external antenna connector on those anyhow. I do however wonder what the issue is still haha. Thanks

Edit: I ordered the new modules, they should be here tomorrow. We will see if that solves the issue for now. I just don't have a ton of time to have to dig into the problem further.

**Comment by truglodite** [comment]
Pretty sure the issue with configs not saving on those devices has to do with bugs in the ESP IDF, as mentioned in issue #6:

https://github.com/flyandi/SquidRID/issues/6#issuecomment-1638692561

The Wroom32u is perhaps one of the best devices for this due to the ease of use and UFl antenna. It's very easy to implement with minimal to no soldering. You could probably get a ufl antenna 32u module w/o dev board and make something smaller/lighter (or hotair a module off a dev board), but then you'd have to deal with all the ancillary circuits to program and run it (3v3 regulator, boot pin, enable pin, CP2101, etc). 

The external antenna is of course a very welcome addition, not only for more range but also for "on drone" units where you might want some extra spacing between rid and RX antennas. It also allows you to make use of any spare high gain wifi antennas you may have laying around. I modified this spare wifi antenna for squidrid:

![IMG_7527](https://github.com/flyandi/SquidRID/assets/18795884/caee6e1d-9130-4432-a887-cdb20b2c5735)

Note I tried this antenna stock with a 3" ufl/sma extension and no other mods. It was +6dbm better than pcb/dipole at my phone (6' separation for this comparison). After soldering that direct ufl cable it got to +9dbm more than pcb/dipole... and it's far lighter/smaller than stock. It's a dual band antenna... but I presume squidrid is only using 2.4. I chose this antenna since it had the highest gain 2.4 section out of my collection.
